### ISSUE TITLE
Add support for logos

### ISSUE THREAD

**Issue by EdwardSafford-NOAA** [danholdaway/eva#131]
## Description

EVA doesn't currently support logos, though they are available in emcpy.  These can be added in a similar fashion to `tight layout`, which was recently added.

## Requirements
Yaml files will be able to specify and plot logo(s -- nws and/or noaa) with appropriate options (location, size, etc).

## Dependencies

None

**Comment by EdwardSafford-NOAA** [comment]
@kevindougherty-noaa I didn't expect a logo per sub-plot; I was figuring one per figure.  Will emcpy support just just one logo on a multi-subplot plot and/or is there a way to explicitly set the location within each sub-plot?  Other than that this looks ok:

![image](https://github.com/JCSDA-internal/eva/assets/62339196/22516054-4f05-4ceb-8a34-cbc78d98beea)

**Comment by kevindougherty-noaa** [comment]
I will have to probably make some code changes to get what you are looking for. I will take a look and get back asap.

**Comment by EdwardSafford-NOAA** [comment]
Seems to be working:
![image](https://github.com/JCSDA-internal/eva/assets/62339196/e463c533-78b9-4967-be84-39adcc1447dd)
