### ISSUE TITLE
Extend mon_data_space.py to support MinMon data

### ISSUE THREAD

**Issue by EdwardSafford-NOAA** [danholdaway/eva#161]
Extend `mon_data_space.py` to support MinMon data.  I wasn't sure this would be necessary but development of a MinMon plotting template for obs-monitor has revealed some things missing from `mon_data_space.py`.  

Reading the MinMon data does not quite work like other sources.  The difference is probably because all monitor data files are generated by Fortran programs, whereas the minmon data files are created by perl using packed, binary format to make them "Fortran-like".  I've figured out a workaround which I need to add.  Also the gnorm plots require the log values of the `allgnorm` variable, but we don't have a log transform available in eva, so I need to add a variable for that.

**Comment by EdwardSafford-NOAA** [comment]
Update:  I have the gnorm and reduction plots working including the 4 cycle gnorm plot.  This one is pretty ugly; usually there's more convergence but the last 4 cycles look to have had some issues.  The plot is good logically though.

![image](https://github.com/JCSDA-internal/eva/assets/62339196/d055695a-9b4d-462c-938a-3b06d7eaf081)

**Comment by EdwardSafford-NOAA** [comment]
Question for @CoryMartin-NOAA and/or @kevindougherty-noaa :  The last MinMon plot I need to implement is the summary.  Right now that's generated by javascript from a csv formatted text file.  In order to reproduce that in `obs-monitor` I'll need to add a means for eva to ingest csv files and generate a dataset.  Does it make sense to add that to `data/mon_obs_space.py` or, because it's not a binary file, create a new `data/*space.py` something like `mon_csv_space.py` ?  Thoughts?

**Comment by CoryMartin-NOAA** [comment]
I think we add in support to eva to read in a CSV, where it is perhaps generic enough so that you can say `columns: [a, b, c, d]` in the YAML and let it define the names you specify for each column?

**Comment by EdwardSafford-NOAA** [comment]
That works for me.  I think I'll wrap up these changes and add `csv_space.py` (or `csv_obs_space.py`?) as a separate issue.

**Comment by CoryMartin-NOAA** [comment]
I would say `csv_space`, no reason why the file we plot would have to be limited to obs, could be wall clock times or memory/disk usage for example.
