### ISSUE TITLE
[Bug] emcpy_horizontal_line.py uses the wrong config

### ISSUE THREAD

**Issue by EdwardSafford-NOAA** [danholdaway/eva#203]
In `emcpy_horizontal_line.py` (line 46) the plot object's config information is modified to remove things that emcpy won't understand, but then the original information (self.config) is returned to the plot object rather than using the `new_config`.  This results in a problem in emcpy because `type` is not a recognized variable and an exception is thrown.

From what I can tell this is a fairly long-standing bug.  I'm surprised I haven't run into it heretofore.  It was an adventure to find but a simple fix.

@kevindougherty-noaa this is the source of that problem I've been having since last week that I thought might have been a build issue.

**Comment by kevindougherty-noaa** [comment]
@EdwardSafford-NOAA Great find! It always is something simple, but a needle in a haystack nonetheless.
