### ISSUE TITLE
Add option(s) to annotate stats on figures

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [danholdaway/eva#36]
Should this be in a legend or somewhere else?

Basically need to have the option to write on the plots things like:

- n
- min
- mean
- max
- std dev
- etc....

**Comment by danholdaway** [comment]
Legend makes sense to me. Could the legend obscure the plot if it gets too large?

**Comment by CoryMartin-NOAA** [comment]
Potentially. Which is why I was thinking something more like this:
![image](https://user-images.githubusercontent.com/6354668/181043291-87787ddd-a046-4801-a49b-31063ddb468c.png)
where it is just annotated either centered under the axis or starting from a corner, etc.

**Comment by danholdaway** [comment]
I like that. Keeps the plot nice and clean while proving all the needed info.

**Comment by CoryMartin-NOAA** [comment]
Starting this work on `feature/stats` but might take a bit to figure out how to do it 'right'
