### ISSUE TITLE
Yaml parsing of single channel results in ABORT

### ISSUE THREAD

**Issue by EdwardSafford-NOAA** [danholdaway/eva#71]
## Current behavior (describe the bug)

Trying to read a single channel value from a yaml file results in an aborted run.

## To Reproduce

What computer are you running on?
Hera

Steps to reproduce the behavior
1. Edit `eva/src/eva/tests/config/testGsiObsSpaceAmsuaMetop-A.yaml` to change `channels: &channels 3,8` to `channels: &channels 3`
2. Run `eva testGsiObsSpaceAmsuaMetop-A.yaml`  The result is thus:

`INFO EvaSetup: Starting Eva`
`INFO GsiObsSpace:   Initializing eva GsiObsSpace object`
`INFO EvaSetup: Running execute for GsiObsSpace`
`ABORT GsiObsSpace: In parse_channel_list the input is neither a list of integers or a string that can be parsed into a list of integers.`
`ABORT`

It's choking on a single channel entry because it is neither a list of integers nor is it a string; it's a single integer.  So parse_channel_list needs to become a bit smarter.

## Expected behavior
Accept a single channel input as well as a comma separated string of multiple channels.

**Comment by EdwardSafford-NOAA** [comment]
@CoryMartin-NOAA I'll be glad to fix this if you can assign it to me.

**Comment by CoryMartin-NOAA** [comment]
Closed through #72
