### ISSUE TITLE
[Bug] Indentation issue in gsi_obs_space.py

### ISSUE THREAD

**Issue by kevindougherty-noaa** [danholdaway/eva#75]
## Current behavior (describe the bug)

@ADCollard identified an issue when he tries to run multiple files using gsi_obs_space.py, he only gets information from the last file in the list.

There should be an indentation on this line here: https://github.com/JCSDA-internal/eva/blob/develop/src/eva/data/gsi_obs_space.py#L238

The `data_collections.create_or_add_to_collection(collection_name, ds, 'nobs')` is outside of the filename loop, which is causing this issue.

**Comment by danholdaway** [comment]
Thanks @kevindougherty-noaa are you going to tackle this? Perhaps we can improve one of the IODA tests to ingest multiple obs files? Say AMSUA-A from 00z and 06z. You could probably cheat and have two copied of the 00z named differently.

**Comment by kevindougherty-noaa** [comment]
@danholdaway I assigned @ADCollard as he said he would not mind tackling it. However, I can as well.

**Comment by ADCollard** [comment]
@danholdaway @kevindougherty-noaa I plan to address this.  Hopefully today.
