### ISSUE TITLE
Fix CI test issue where it fails to download shapefiles

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [danholdaway/eva#87]
## Current behavior (describe the bug)

As the title says, CI testing that previously worked now gives a segmentation fault. Seems to be when attempting to download shapefiles for the map plotting.

**Comment by climbfuji** [comment]
Do you think it makes sense to move to the spack-stack containers that we maintain for JEDI?

**Comment by CoryMartin-NOAA** [comment]
@climbfuji as opposed to the GitHub actions default hosted environment? Probably eventually not a bad idea, but for eva that might be a bit overkill (not sure). @danholdaway any thoughts?

**Comment by climbfuji** [comment]
> @climbfuji as opposed to the GitHub actions default hosted environment? Probably eventually not a bad idea, but for eva that might be a bit overkill (not sure). @danholdaway any thoughts?

It should also be possible to just grab the containers from dockerhub and run them on the github environment. In the long run it might be worth moving to the JEDI CI/CD environment, though.
